from flask_sqlalchemy import SQLAlchemy
from datetime import datetime
import json

db = SQLAlchemy()

class Trade(db.Model):
    """Records of actual trades made"""
    __tablename__ = 'trades'
    
    id = db.Column(db.Integer, primary_key=True)
    symbol = db.Column(db.String(10), nullable=False, index=True)
    trade_type = db.Column(db.String(10), nullable=False)  # 'BUY' or 'SELL'
    entry_price = db.Column(db.Float, nullable=False)
    exit_price = db.Column(db.Float, nullable=True)
    quantity = db.Column(db.Integer, nullable=False)
    entry_time = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    exit_time = db.Column(db.DateTime, nullable=True)
    profit_loss = db.Column(db.Float, nullable=True)
    profit_loss_percent = db.Column(db.Float, nullable=True)
    status = db.Column(db.String(20), nullable=False, default='OPEN')  # OPEN, CLOSED, CANCELLED
    notes = db.Column(db.Text, nullable=True)
    
    def calculate_pnl(self):
        """Calculate profit/loss for closed trades"""
        if self.exit_price and self.status == 'CLOSED':
            if self.trade_type == 'BUY':
                self.profit_loss = (self.exit_price - self.entry_price) * self.quantity
                self.profit_loss_percent = ((self.exit_price - self.entry_price) / self.entry_price) * 100
            elif self.trade_type == 'SELL':
                self.profit_loss = (self.entry_price - self.exit_price) * self.quantity
                self.profit_loss_percent = ((self.entry_price - self.exit_price) / self.entry_price) * 100

class Signal(db.Model):
    """Trading signals generated by strategies"""
    __tablename__ = 'signals'
    
    id = db.Column(db.Integer, primary_key=True)
    symbol = db.Column(db.String(10), nullable=False, index=True)
    signal_type = db.Column(db.String(10), nullable=False)  # 'BUY' or 'SELL'
    confidence_score = db.Column(db.Float, nullable=False)  # 0-1
    current_price = db.Column(db.Float, nullable=False)
    timestamp = db.Column(db.DateTime, nullable=False, default=datetime.utcnow, index=True)
    strategy_details = db.Column(db.Text, nullable=True)  # JSON string of contributing strategies
    acted_upon = db.Column(db.Boolean, default=False)
    trade_id = db.Column(db.Integer, db.ForeignKey('trades.id'), nullable=True)
    
    def get_strategy_details(self):
        """Parse strategy details JSON"""
        if self.strategy_details:
            return json.loads(self.strategy_details)
        return {}

class StrategyPerformance(db.Model):
    """Tracks performance of individual strategies"""
    __tablename__ = 'strategy_performance'
    
    id = db.Column(db.Integer, primary_key=True)
    strategy_name = db.Column(db.String(50), nullable=False, index=True)
    symbol = db.Column(db.String(10), nullable=False)
    total_signals = db.Column(db.Integer, default=0)
    winning_signals = db.Column(db.Integer, default=0)
    losing_signals = db.Column(db.Integer, default=0)
    win_rate = db.Column(db.Float, default=0.0)  # percentage
    avg_profit = db.Column(db.Float, default=0.0)
    avg_loss = db.Column(db.Float, default=0.0)
    last_updated = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    
    def calculate_win_rate(self):
        """Calculate win rate percentage"""
        total = self.winning_signals + self.losing_signals
        if total > 0:
            self.win_rate = (self.winning_signals / total) * 100

class MLModel(db.Model):
    """Stores ML model metadata and versions"""
    __tablename__ = 'ml_models'
    
    id = db.Column(db.Integer, primary_key=True)
    model_name = db.Column(db.String(100), nullable=False)
    model_type = db.Column(db.String(50), nullable=False)  # Neural Network, Random Forest, etc.
    version = db.Column(db.Integer, nullable=False)
    accuracy = db.Column(db.Float, nullable=True)
    training_samples = db.Column(db.Integer, nullable=True)
    created_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    last_retrained = db.Column(db.DateTime, nullable=True)
    is_active = db.Column(db.Boolean, default=True)
    model_path = db.Column(db.String(255), nullable=True)  # Path to saved model
